### ISSUE TITLE
Update the modpack | Mettre à jour le modpack

### ISSUE THREAD

**Issue by v1r4lv0rt3x** [lion05110/mod#2]
- [x] Mettre le mod pack à jour
- [x] Changer les mods
- [x] Relancer le serveur

**Comment by lion05110** [comment]
Tu trouvera les mods à cette adresse:
lion05110/mod2 (github.com)<https://github.com/lion05110/mod2>
________________________________
De : Binarydoc.fr ***@***.***>
Envoyé : jeudi 25 janvier 2024 17:56
À : lion05110/mod ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [lion05110/mod] Update the modpack | Mettre à jour le modpack (Issue #2)


  *    Mettre le mod pack à jour
  *    Changer les mods
  *    Relancer le serveur

**Comment by v1r4lv0rt3x** [comment]
- [x] Perfect
